let siswa=[],editId=null,jenisKeu=[],mapel=[],nilai=[];const $=id=>document.getElementById(id),rp=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n||0),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),today=()=>new Date().toISOString().slice(0,10);
async function get(q){const r=await q;if(r.error){console.warn(r.error.message);return[]}return r.data||[]}
async function cek(){const{data:{session}}=await supabaseClient.auth.getSession();if(!session)return location.replace("login.html");await muat()}
async function muat(){const[s,a,t,j,p,m,n]=await Promise.all([get(supabaseClient.from("siswa").select("*").eq("aktif",true).order("nomor_absen")),get(supabaseClient.from("absensi").select("*").eq("tanggal",today()).order("created_at",{ascending:true})),get(supabaseClient.from("transaksi_tabungan").select("*").order("tanggal",{ascending:false})),get(supabaseClient.from("jenis_keuangan").select("*").eq("aktif",true)),get(supabaseClient.from("pembayaran_siswa").select("*,jenis_keuangan(nama)").order("tanggal",{ascending:false})),get(supabaseClient.from("mapel").select("*").order("nama")),get(supabaseClient.from("nilai").select("*").order("created_at",{ascending:false}))]);siswa=s;jenisKeu=j;mapel=m;nilai=n;$("jml").textContent=s.length;$("hadir").textContent=a.filter(x=>x.status==="Hadir").length;$("saldo").textContent=rp(t.reduce((z,x)=>z+(x.jenis==="Setoran"?+x.jumlah:-x.jumlah),0));$("bayar").textContent=rp(p.reduce((z,x)=>z+(+x.jumlah),0));renderPertama(a);renderSiswa();renderAbs(a);renderSelect();renderTab(t);renderBayar(p);renderMapel();renderNilai();renderRekap()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>openPage(b.dataset.page));function openPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id))}
function renderPertama(a){$("tbPertama").innerHTML=a.filter(x=>x.status==="Hadir").slice(0,5).map((x,i)=>{const s=siswa.find(v=>v.id===x.siswa_id),jam=x.created_at?new Date(x.created_at).toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"}):"-";return`<tr><td><b>#${i+1}</b></td><td>${s?.nomor_absen||"-"}</td><td>${esc(s?.nama||"-")}</td><td>${jam}</td></tr>`}).join("")||'<tr><td colspan="4">Belum ada siswa hadir.</td></tr>'}
function renderSiswa(){const q=($("cari").value||"").toLowerCase();$("tbSiswa").innerHTML=siswa.filter(x=>x.nama.toLowerCase().includes(q)||(x.nisn||"").includes(q)).map(x=>`<tr><td>${x.nomor_absen}</td><td><b>${esc(x.nama)}</b></td><td>${esc(x.nis||"-")}</td><td>${esc(x.nisn||"-")}</td><td>${esc(x.jenis_kelamin)}</td><td><button class="small" onclick="editS('${x.id}')">Edit</button> <button class="small danger" onclick="hapusS('${x.id}')">Hapus</button></td></tr>`).join("")}
function bukaModal(){editId=null;$("fSiswa").reset();$("modal").classList.add("active")}function tutupModal(){$("modal").classList.remove("active")}function editS(id){const x=siswa.find(v=>v.id===id);editId=id;$("nama").value=x.nama;$("nis").value=x.nis||"";$("nisn").value=x.nisn||"";$("absen").value=x.nomor_absen;$("jk").value=x.jenis_kelamin;$("modal").classList.add("active")}
$("fSiswa").onsubmit=async e=>{e.preventDefault();const row={nama:$("nama").value.trim(),nis:$("nis").value.trim()||null,nisn:$("nisn").value.trim(),nomor_absen:+$("absen").value,jenis_kelamin:$("jk").value,kelas:"5",aktif:true},q=editId?supabaseClient.from("siswa").update(row).eq("id",editId):supabaseClient.from("siswa").insert(row),{error}=await q;if(error)return alert(error.message);tutupModal();muat()};async function hapusS(id){if(confirm("Nonaktifkan siswa?")){await supabaseClient.from("siswa").update({aktif:false}).eq("id",id);muat()}}
function renderAbs(a){const d=new Map(a.map(x=>[x.siswa_id,x.status]));$("tbAbs").innerHTML=siswa.map(x=>`<tr><td>${x.nomor_absen}</td><td>${esc(x.nama)}</td><td><select id="abs-${x.id}">${["Hadir","Sakit","Izin","Alpa"].map(o=>`<option${d.get(x.id)===o?" selected":""}>${o}</option>`).join("")}</select></td></tr>`).join("")}
async function simpanAbsensi(){const rows=siswa.map(x=>({siswa_id:x.id,tanggal:$("tglAbs").value,status:$("abs-"+x.id).value,metode:"Manual"})),{error}=await supabaseClient.from("absensi").upsert(rows,{onConflict:"siswa_id,tanggal"});if(error)return alert(error.message);alert("Absensi tersimpan");muat()}
function renderSelect(){const o='<option value="">Pilih siswa</option>'+siswa.map(x=>`<option value="${x.id}">${x.nomor_absen}. ${esc(x.nama)}</option>`).join("");["tabSiswa","bySiswa","nilaiSiswa"].forEach(id=>$(id).innerHTML=o);$("byJenis").innerHTML='<option value="">Pilih pembayaran</option>'+jenisKeu.map(x=>`<option value="${x.id}" data-n="${x.nominal_tagihan}">${esc(x.nama)}</option>`).join("");$("nilaiMapel").innerHTML='<option value="">Pilih mapel</option>'+mapel.map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join("")}
$("byJenis").onchange=()=>{$("byJumlah").value=$("byJenis").selectedOptions[0]?.dataset.n||""};
$("fTab").onsubmit=async e=>{e.preventDefault();const{error}=await supabaseClient.from("transaksi_tabungan").insert({siswa_id:$("tabSiswa").value,jenis:$("tabJenis").value,jumlah:+$("tabJumlah").value,keterangan:$("tabKet").value});if(error)return alert(error.message);e.target.reset();muat()};function renderTab(d){$("tbTab").innerHTML=d.map(x=>`<tr><td>${x.tanggal}</td><td>${esc(siswa.find(s=>s.id===x.siswa_id)?.nama||"-")}</td><td>${x.jenis}</td><td>${rp(x.jumlah)}</td></tr>`).join("")}
$("fJenis").onsubmit=async e=>{e.preventDefault();const{error}=await supabaseClient.from("jenis_keuangan").insert({nama:$("jkNama").value,kategori:$("jkKategori").value,nominal_tagihan:+$("jkNominal").value,periode:$("jkPeriode").value,aktif:true});if(error)return alert(error.message);e.target.reset();muat()};$("fBayar").onsubmit=async e=>{e.preventDefault();const{error}=await supabaseClient.from("pembayaran_siswa").insert({siswa_id:$("bySiswa").value,jenis_keuangan_id:$("byJenis").value,jumlah:+$("byJumlah").value,metode:$("byMetode").value});if(error)return alert(error.message);e.target.reset();muat()};function renderBayar(d){$("tbBayar").innerHTML=d.map(x=>`<tr><td>${x.tanggal}</td><td>${esc(siswa.find(s=>s.id===x.siswa_id)?.nama||"-")}</td><td>${esc(x.jenis_keuangan?.nama||"-")}</td><td>${rp(x.jumlah)}</td></tr>`).join("")}
function tabKeu(id,b){document.querySelectorAll(".keu").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");b.classList.add("active")}
$("fMapel").onsubmit=async e=>{e.preventDefault();const{error}=await supabaseClient.from("mapel").insert({nama:$("namaMapel").value.trim()});if(error)return alert(error.message);e.target.reset();muat()};function renderMapel(){$("tbMapel").innerHTML=mapel.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.nama)}</td><td><button class="small danger" onclick="hapusMapel('${x.id}')">Hapus</button></td></tr>`).join("")};async function hapusMapel(id){if(confirm("Hapus mapel?")){await supabaseClient.from("mapel").delete().eq("id",id);muat()}}
$("fNilai").onsubmit=async e=>{e.preventDefault();const{error}=await supabaseClient.from("nilai").insert({semester:+$("nilaiSemester").value,siswa_id:$("nilaiSiswa").value,mapel_id:$("nilaiMapel").value,jenis_penilaian:$("nilaiJenis").value,kegiatan:$("nilaiKegiatan").value,nilai:+$("nilaiAngka").value});if(error)return alert(error.message);e.target.reset();muat()};function renderNilai(){$("tbNilai").innerHTML=nilai.map(x=>`<tr><td>${x.semester}</td><td>${esc(siswa.find(s=>s.id===x.siswa_id)?.nama||"-")}</td><td>${esc(mapel.find(m=>m.id===x.mapel_id)?.nama||"-")}</td><td>${esc(x.jenis_penilaian||"-")}</td><td>${esc(x.kegiatan||"-")}</td><td><b>${x.nilai}</b></td><td><button class="small danger" onclick="hapusNilai('${x.id}')">Hapus</button></td></tr>`).join("")};async function hapusNilai(id){if(confirm("Hapus nilai?")){await supabaseClient.from("nilai").delete().eq("id",id);muat()}}
function renderRekap(){const sem=+$("rekapSemester").value,g={};nilai.filter(x=>+x.semester===sem).forEach(x=>{const k=x.siswa_id+"|"+x.mapel_id;(g[k]??=[]).push(+x.nilai)});$("tbRekap").innerHTML=Object.entries(g).map(([k,v])=>{const[a,b]=k.split("|");return`<tr><td>${esc(siswa.find(s=>s.id===a)?.nama||"-")}</td><td>${esc(mapel.find(m=>m.id===b)?.nama||"-")}</td><td>${v.length}</td><td><b>${(v.reduce((z,n)=>z+n,0)/v.length).toFixed(1)}</b></td></tr>`}).join("")}
async function keluar(){await supabaseClient.auth.signOut();location.href="index.html"}$("today").textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});$("tglAbs").value=today();cek();