let siswa=[],editId=null,jenisKeu=[];
const $=id=>document.getElementById(id),rp=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n||0),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function cek(){const{data:{session}}=await supabaseClient.auth.getSession();if(!session)return location.replace("login.html");const{data:p}=await supabaseClient.from("profil_pengguna").select("peran").eq("id",session.user.id).single();if(p?.peran!=="guru")return location.replace("login.html");await muat()}
async function muat(){const[{data:s},{data:a},{data:t},{data:j},{data:p}]=await Promise.all([supabaseClient.from("siswa").select("*").eq("aktif",true).order("nomor_absen"),supabaseClient.from("absensi").select("*").eq("tanggal",new Date().toISOString().slice(0,10)),supabaseClient.from("transaksi_tabungan").select("*").order("tanggal",{ascending:false}),supabaseClient.from("jenis_keuangan").select("*").eq("aktif",true),supabaseClient.from("pembayaran_siswa").select("*,jenis_keuangan(nama)").order("tanggal",{ascending:false})]);siswa=s||[];jenisKeu=j||[];$("jml").textContent=siswa.length;$("hadir").textContent=(a||[]).filter(x=>x.status==="Hadir").length;$("saldo").textContent=rp((t||[]).reduce((z,x)=>z+(x.jenis==="Setoran"?Number(x.jumlah):-Number(x.jumlah)),0));$("bayar").textContent=rp((p||[]).reduce((z,x)=>z+Number(x.jumlah),0));renderSiswa();renderAbs();renderSelect();renderTab(t||[]);renderBayar(p||[])}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>openPage(b.dataset.page));function openPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id))}
function renderSiswa(){const q=($("cari")?.value||"").toLowerCase();$("tbSiswa").innerHTML=siswa.filter(x=>x.nama.toLowerCase().includes(q)||(x.nisn||"").includes(q)).map(x=>`<tr><td>${x.nomor_absen}</td><td><b>${esc(x.nama)}</b></td><td>${esc(x.nis||"-")}</td><td>${esc(x.nisn||"-")}</td><td>${esc(x.jenis_kelamin)}</td><td><button class="small" onclick="editS('${x.id}')">Edit</button> <button class="small danger" onclick="hapusS('${x.id}')">Hapus</button></td></tr>`).join("")||'<tr><td colspan="6">Belum ada siswa.</td></tr>'}
function bukaModal(){editId=null;$("fSiswa").reset();$("modalTitle").textContent="Tambah Siswa";$("modal").classList.add("active")}function tutupModal(){$("modal").classList.remove("active")}function editS(id){const x=siswa.find(v=>v.id===id);editId=id;$("nama").value=x.nama;$("nis").value=x.nis||"";$("nisn").value=x.nisn||"";$("absen").value=x.nomor_absen;$("jk").value=x.jenis_kelamin;$("modalTitle").textContent="Edit Siswa";$("modal").classList.add("active")}
$("fSiswa").onsubmit=async e=>{e.preventDefault();const row={nama:$("nama").value.trim(),nis:$("nis").value.trim()||null,nisn:$("nisn").value.trim(),nomor_absen:Number($("absen").value),jenis_kelamin:$("jk").value,kelas:"5",aktif:true};const q=editId?supabaseClient.from("siswa").update(row).eq("id",editId):supabaseClient.from("siswa").insert(row);const{error}=await q;if(error)return alert(error.message);tutupModal();await muat()}
async function hapusS(id){if(!confirm("Nonaktifkan siswa ini?"))return;await supabaseClient.from("siswa").update({aktif:false}).eq("id",id);await muat()}
function renderAbs(){const opts=`<option>Hadir</option><option>Sakit</option><option>Izin</option><option>Alpa</option>`;$("tbAbs").innerHTML=siswa.map(x=>`<tr><td>${x.nomor_absen}</td><td>${esc(x.nama)}</td><td><select id="abs-${x.id}">${opts}</select></td></tr>`).join("")}
async function simpanAbsensi(){const tanggal=$("tglAbs").value,rows=siswa.map(x=>({siswa_id:x.id,tanggal,status:$("abs-"+x.id).value,metode:"Manual"}));const{error}=await supabaseClient.from("absensi").upsert(rows,{onConflict:"siswa_id,tanggal"});if(error)return alert(error.message);alert("Absensi tersimpan");await muat()}
function renderSelect(){const o='<option value="">Pilih siswa</option>'+siswa.map(x=>`<option value="${x.id}">${x.nomor_absen}. ${esc(x.nama)}</option>`).join("");$("tabSiswa").innerHTML=o;$("bySiswa").innerHTML=o;$("byJenis").innerHTML='<option value="">Pilih pembayaran</option>'+jenisKeu.map(x=>`<option value="${x.id}" data-n="${x.nominal_tagihan}">${esc(x.nama)} - ${rp(x.nominal_tagihan)}</option>`).join("")}
$("byJenis").onchange=()=>{const o=$("byJenis").selectedOptions[0];if(o?.dataset.n)$("byJumlah").value=o.dataset.n}
$("fTab").onsubmit=async e=>{e.preventDefault();const{error}=await supabaseClient.from("transaksi_tabungan").insert({siswa_id:$("tabSiswa").value,jenis:$("tabJenis").value,jumlah:Number($("tabJumlah").value),keterangan:$("tabKet").value.trim()});if(error)return alert(error.message);e.target.reset();await muat()}
function renderTab(d){$("tbTab").innerHTML=d.map(x=>{const s=siswa.find(v=>v.id===x.siswa_id);return`<tr><td>${x.tanggal}</td><td>${esc(s?.nama||"-")}</td><td>${x.jenis}</td><td>${rp(x.jumlah)}</td><td>${esc(x.keterangan||"-")}</td></tr>`}).join("")}
$("fJenis").onsubmit=async e=>{e.preventDefault();const{error}=await supabaseClient.from("jenis_keuangan").insert({nama:$("jkNama").value.trim(),kategori:$("jkKategori").value,nominal_tagihan:Number($("jkNominal").value),periode:$("jkPeriode").value.trim()});if(error)return alert(error.message);e.target.reset();await muat()}
$("fBayar").onsubmit=async e=>{e.preventDefault();const metode=$("byMetode").value,jumlah=Number($("byJumlah").value),sid=$("bySiswa").value,jid=$("byJenis").value;if(metode==="Potong Tabungan"){if(!confirm("Pastikan ada persetujuan orang tua. Lanjut potong tabungan?"))return;const{error:t}=await supabaseClient.from("transaksi_tabungan").insert({siswa_id:sid,jenis:"Penarikan",jumlah,keterangan:"Pembayaran kelas melalui potong tabungan"});if(t)return alert(t.message)}const{error}=await supabaseClient.from("pembayaran_siswa").insert({siswa_id:sid,jenis_keuangan_id:jid,jumlah,metode,persetujuan_wali:metode==="Potong Tabungan"});if(error)return alert(error.message);e.target.reset();await muat()}
function renderBayar(d){$("tbBayar").innerHTML=d.map(x=>{const s=siswa.find(v=>v.id===x.siswa_id);return`<tr><td>${x.tanggal}</td><td>${esc(s?.nama||"-")}</td><td>${esc(x.jenis_keuangan?.nama||"-")}</td><td>${x.metode}</td><td>${rp(x.jumlah)}</td></tr>`}).join("")}
function tabKeu(id,b){document.querySelectorAll(".keu").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");b.classList.add("active")}
async function keluar(){await supabaseClient.auth.signOut();location.href="index.html"}
$("today").textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});$("tglAbs").value=new Date().toISOString().slice(0,10);cek();